### ISSUE TITLE
Clarify relation to flx

### ISSUE THREAD

**Issue by tarsius** [jcs-elpa/sublime-fuzzy#1]
You write

> This is the same with flx created by lewang,

that's grammatically incorrect and should be

> This is the same as flx created by lewang,

but it is unclear to me what it means for them to "be the same". I assume this means:

> This uses the same algorithm as used by flx (created by lewang),

in which case you should write that or something similar.

**Comment by jcs090218** [comment]
Sorry for not responding to this. I must have forgotten about this issue... 

This package is an experiment package to the upstream; if user want to use this package should look at the upstream and compare the differences!

**Comment by tarsius** [comment]
Np. Cheers!
